<?php

namespace app\modules\admin\models;

use yii\web\UploadedFile;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property int $category_id
 * @property string $title
 * @property string $content
 * @property string $price
 * @property string $old_price
 * @property string $description
 * @property string $keywords
 * @property string $img
 * @property int $is_offer
 */
class Product extends ActiveRecord {

    public $file;

    public static function tableName() {
        return 'product';
    }

    public function getCategory() {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }

    public function rules() {
        return [
            [['category_id', 'title', 'content'], 'required'],
            [['category_id', 'is_offer'], 'integer'],
            [['content'], 'string'],
            [['price', 'old_price'], 'number'],
            [['price', 'old_price'], 'default', 'value' => 0],
            [['img'], 'default', 'value' => 'products/no-image.png'],
            [['title', 'description', 'keywords', 'img'], 'string', 'max' => 255],
            [['file'], 'image'],
        ];
    }

    public function attributeLabels() {
        return [
            'id' => 'ID',
            'category_id' => 'Родительская категория',
            'title' => 'Название',
            'content' => 'Описание',
            'price' => 'Цена',
            'old_price' => 'Старая цена',
            'description' => 'Описание',
            'keywords' => 'Ключевики',
            'img' => 'Фото',
            'file' => 'Фото',
            'is_offer' => 'Предложение',
        ];
    }

    public function beforeSave($insert) {
        if($file = UploadedFile::getInstance($this, 'file')) {
            $dir = 'products/' . date("Y-m-d") . '/';
            if(!is_dir($dir)) {
                mkdir($dir);
            }
            $file_name = uniqid() . '_' . $file->baseName . '.' . $file->extension;
            $this->img = $dir . $file_name;
            $file->saveAs($this->img);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}